name: genieclass_streaming_mobile
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.2.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

  flutter_riverpod: ^2.5.1
  
  dio: ^5.3.2
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  alice_lightweight: ^3.8.0
  pretty_dio_logger: ^1.3.1

  json_serializable: 6.8.0
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  intl: ^0.18.1

  either_dart: ^1.0.0
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  # connectivity_plus: ^6.0.2

  permission_handler: ^10.2.0

  # firebase_core: ^2.20.0
  # firebase_remote_config: ^4.2.6
  # firebase_analytics: ^10.5.0
  
  cached_network_image: ^3.3.0
  infinite_scroll_pagination: ^4.0.0

  bot_toast: ^4.1.1

  livekit_client: ^2.2.4
  camerawesome: ^2.0.0
  dotted_border: 2.1.0

  # video player
  chewie: 1.8.1
  video_player: 2.8.6

  # svg
  flutter_svg: 2.0.10+1

  # lottie
  lottie: 3.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cfg/config.env
    - assets/images/
    - assets/illustrations/
    - assets/fonts/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.genieclass_streaming_mobile
    iosBundleIdentifier: com.example.genieclassStreamingMobile
